# kubectl run nginx --image=nginx --port=80 --dry-run=client -o yaml > 04-nginx-port.yaml
# Set image new image of the pod
# kubectl set image pod/nginx nginx=nginx:1.7.1
apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: nginx
  name: nginx
spec:
  containers:
  - image: nginx
    name: nginx
    ports:
    - containerPort: 80
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
